// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: IM.Enum.proto

package me.ele.cs.push.protobuf;

public final class IMEnum {
  private IMEnum() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  /**
   * Protobuf enum {@code IM.Enum.LoginStatus}
   */
  public enum LoginStatus
      implements com.google.protobuf.Internal.EnumLite {
    /**
     * <code>SUCESS = 1;</code>
     */
    SUCESS(1),
    /**
     * <code>USER_NOT_EXISTS = 2;</code>
     */
    USER_NOT_EXISTS(2),
    /**
     * <code>PASSWORD_ERROR = 3;</code>
     */
    PASSWORD_ERROR(3),
    ;

    /**
     * <code>SUCESS = 1;</code>
     */
    public static final int SUCESS_VALUE = 1;
    /**
     * <code>USER_NOT_EXISTS = 2;</code>
     */
    public static final int USER_NOT_EXISTS_VALUE = 2;
    /**
     * <code>PASSWORD_ERROR = 3;</code>
     */
    public static final int PASSWORD_ERROR_VALUE = 3;


    public final int getNumber() {
      return value;
    }

    public static LoginStatus valueOf(int value) {
      switch (value) {
        case 1: return SUCESS;
        case 2: return USER_NOT_EXISTS;
        case 3: return PASSWORD_ERROR;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<LoginStatus>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        LoginStatus> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<LoginStatus>() {
            public LoginStatus findValueByNumber(int number) {
              return LoginStatus.valueOf(number);
            }
          };

    private final int value;

    private LoginStatus(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:IM.Enum.LoginStatus)
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
