// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: IM.Message.proto

package me.ele.cs.push.protobuf;

public final class IMMessage {
  private IMMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface LoginRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:IM.Message.LoginRequest)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>required string user_name = 1;</code>
     */
    boolean hasUserName();
    /**
     * <code>required string user_name = 1;</code>
     */
    java.lang.String getUserName();
    /**
     * <code>required string user_name = 1;</code>
     */
    com.google.protobuf.ByteString
        getUserNameBytes();

    /**
     * <code>required string password = 2;</code>
     */
    boolean hasPassword();
    /**
     * <code>required string password = 2;</code>
     */
    java.lang.String getPassword();
    /**
     * <code>required string password = 2;</code>
     */
    com.google.protobuf.ByteString
        getPasswordBytes();
  }
  /**
   * Protobuf type {@code IM.Message.LoginRequest}
   */
  public  static final class LoginRequest extends
      com.google.protobuf.GeneratedMessageLite<
          LoginRequest, LoginRequest.Builder> implements
      // @@protoc_insertion_point(message_implements:IM.Message.LoginRequest)
      LoginRequestOrBuilder {
    private LoginRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      userName_ = "";
      password_ = "";
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(tag, input)) {
                done = true;
              }
              break;
            }
            case 10: {
              String s = input.readString();
              bitField0_ |= 0x00000001;
              userName_ = s;
              break;
            }
            case 18: {
              String s = input.readString();
              bitField0_ |= 0x00000002;
              password_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        doneParsing();
      }
    }
    private int bitField0_;
    public static final int USER_NAME_FIELD_NUMBER = 1;
    private java.lang.String userName_;
    /**
     * <code>required string user_name = 1;</code>
     */
    public boolean hasUserName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string user_name = 1;</code>
     */
    public java.lang.String getUserName() {
      return userName_;
    }
    /**
     * <code>required string user_name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getUserNameBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(userName_);
    }
    /**
     * <code>required string user_name = 1;</code>
     */
    private void setUserName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      userName_ = value;
    }
    /**
     * <code>required string user_name = 1;</code>
     */
    private void clearUserName() {
      bitField0_ = (bitField0_ & ~0x00000001);
      userName_ = getDefaultInstance().getUserName();
    }
    /**
     * <code>required string user_name = 1;</code>
     */
    private void setUserNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      userName_ = value.toStringUtf8();
    }

    public static final int PASSWORD_FIELD_NUMBER = 2;
    private java.lang.String password_;
    /**
     * <code>required string password = 2;</code>
     */
    public boolean hasPassword() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string password = 2;</code>
     */
    public java.lang.String getPassword() {
      return password_;
    }
    /**
     * <code>required string password = 2;</code>
     */
    public com.google.protobuf.ByteString
        getPasswordBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(password_);
    }
    /**
     * <code>required string password = 2;</code>
     */
    private void setPassword(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      password_ = value;
    }
    /**
     * <code>required string password = 2;</code>
     */
    private void clearPassword() {
      bitField0_ = (bitField0_ & ~0x00000002);
      password_ = getDefaultInstance().getPassword();
    }
    /**
     * <code>required string password = 2;</code>
     */
    private void setPasswordBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      password_ = value.toStringUtf8();
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeString(1, getUserName());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeString(2, getPassword());
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getUserName());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getPassword());
      }
      size += unknownFields.getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static me.ele.cs.push.protobuf.IMMessage.LoginRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return parser().parseFrom(data);
    }
    public static me.ele.cs.push.protobuf.IMMessage.LoginRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return parser().parseFrom(data, extensionRegistry);
    }
    public static me.ele.cs.push.protobuf.IMMessage.LoginRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return parser().parseFrom(data);
    }
    public static me.ele.cs.push.protobuf.IMMessage.LoginRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return parser().parseFrom(data, extensionRegistry);
    }
    public static me.ele.cs.push.protobuf.IMMessage.LoginRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parser().parseFrom(input);
    }
    public static me.ele.cs.push.protobuf.IMMessage.LoginRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parser().parseFrom(input, extensionRegistry);
    }
    public static me.ele.cs.push.protobuf.IMMessage.LoginRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parser().parseDelimitedFrom(input);
    }
    public static me.ele.cs.push.protobuf.IMMessage.LoginRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parser().parseDelimitedFrom(input, extensionRegistry);
    }
    public static me.ele.cs.push.protobuf.IMMessage.LoginRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return parser().parseFrom(input);
    }
    public static me.ele.cs.push.protobuf.IMMessage.LoginRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parser().parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(me.ele.cs.push.protobuf.IMMessage.LoginRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code IM.Message.LoginRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          me.ele.cs.push.protobuf.IMMessage.LoginRequest, Builder> implements
        // @@protoc_insertion_point(builder_implements:IM.Message.LoginRequest)
        me.ele.cs.push.protobuf.IMMessage.LoginRequestOrBuilder {
      // Construct using me.ele.cs.push.protobuf.IMMessage.LoginRequest.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>required string user_name = 1;</code>
       */
      public boolean hasUserName() {
        return instance.hasUserName();
      }
      /**
       * <code>required string user_name = 1;</code>
       */
      public java.lang.String getUserName() {
        return instance.getUserName();
      }
      /**
       * <code>required string user_name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getUserNameBytes() {
        return instance.getUserNameBytes();
      }
      /**
       * <code>required string user_name = 1;</code>
       */
      public Builder setUserName(
          java.lang.String value) {
        copyOnWrite();
        instance.setUserName(value);
        return this;
      }
      /**
       * <code>required string user_name = 1;</code>
       */
      public Builder clearUserName() {
        copyOnWrite();
        instance.clearUserName();
        return this;
      }
      /**
       * <code>required string user_name = 1;</code>
       */
      public Builder setUserNameBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setUserNameBytes(value);
        return this;
      }

      /**
       * <code>required string password = 2;</code>
       */
      public boolean hasPassword() {
        return instance.hasPassword();
      }
      /**
       * <code>required string password = 2;</code>
       */
      public java.lang.String getPassword() {
        return instance.getPassword();
      }
      /**
       * <code>required string password = 2;</code>
       */
      public com.google.protobuf.ByteString
          getPasswordBytes() {
        return instance.getPasswordBytes();
      }
      /**
       * <code>required string password = 2;</code>
       */
      public Builder setPassword(
          java.lang.String value) {
        copyOnWrite();
        instance.setPassword(value);
        return this;
      }
      /**
       * <code>required string password = 2;</code>
       */
      public Builder clearPassword() {
        copyOnWrite();
        instance.clearPassword();
        return this;
      }
      /**
       * <code>required string password = 2;</code>
       */
      public Builder setPasswordBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setPasswordBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:IM.Message.LoginRequest)
    }
    private byte memoizedIsInitialized = -1;
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case PARSE_PARTIAL_FROM: {
          return new me.ele.cs.push.protobuf.IMMessage.LoginRequest(          (com.google.protobuf.CodedInputStream) arg0,
              (com.google.protobuf.ExtensionRegistryLite) arg1);
        }
        case NEW_INSTANCE: {
          return new me.ele.cs.push.protobuf.IMMessage.LoginRequest(
              com.google.protobuf.Internal.EMPTY_CODED_INPUT_STREAM,
              com.google.protobuf.ExtensionRegistryLite
                  .getEmptyRegistry());
        }
        case IS_INITIALIZED: {
          byte isInitialized = memoizedIsInitialized;
          if (isInitialized == 1) return DEFAULT_INSTANCE;
          if (isInitialized == 0) return null;

          boolean shouldMemoize = ((Boolean) arg0).booleanValue();
          if (!hasUserName()) {
            if (shouldMemoize) {
              memoizedIsInitialized = 0;
            }
            return null;
          }
          if (!hasPassword()) {
            if (shouldMemoize) {
              memoizedIsInitialized = 0;
            }
            return null;
          }
          if (shouldMemoize) memoizedIsInitialized = 1;
          return DEFAULT_INSTANCE;

        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case MERGE_FROM: {
          if (arg0 == me.ele.cs.push.protobuf.IMMessage.LoginRequest.getDefaultInstance()) return this;
          me.ele.cs.push.protobuf.IMMessage.LoginRequest other = (me.ele.cs.push.protobuf.IMMessage.LoginRequest) arg0;
          if (other.hasUserName()) {
            bitField0_ |= 0x00000001;
            userName_ = other.userName_;
            
          }
          if (other.hasPassword()) {
            bitField0_ |= 0x00000002;
            password_ = other.password_;
            
          }
          this.mergeUnknownFields(other.unknownFields);
          return this;
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (me.ele.cs.push.protobuf.IMMessage.LoginRequest.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:IM.Message.LoginRequest)
    private static final me.ele.cs.push.protobuf.IMMessage.LoginRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new LoginRequest(
          com.google.protobuf.Internal
              .EMPTY_CODED_INPUT_STREAM,
          com.google.protobuf.ExtensionRegistryLite
              .getEmptyRegistry());
    }

    public static me.ele.cs.push.protobuf.IMMessage.LoginRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<LoginRequest> PARSER;

    public static com.google.protobuf.Parser<LoginRequest> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface LoginResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:IM.Message.LoginResponse)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>required .IM.Enum.LoginStatus status = 1;</code>
     */
    boolean hasStatus();
    /**
     * <code>required .IM.Enum.LoginStatus status = 1;</code>
     */
    me.ele.cs.push.protobuf.IMEnum.LoginStatus getStatus();
  }
  /**
   * Protobuf type {@code IM.Message.LoginResponse}
   */
  public  static final class LoginResponse extends
      com.google.protobuf.GeneratedMessageLite<
          LoginResponse, LoginResponse.Builder> implements
      // @@protoc_insertion_point(message_implements:IM.Message.LoginResponse)
      LoginResponseOrBuilder {
    private LoginResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      status_ = 1;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(tag, input)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              me.ele.cs.push.protobuf.IMEnum.LoginStatus value = me.ele.cs.push.protobuf.IMEnum.LoginStatus.valueOf(rawValue);
              if (value == null) {
                super.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                status_ = rawValue;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        doneParsing();
      }
    }
    private int bitField0_;
    public static final int STATUS_FIELD_NUMBER = 1;
    private int status_;
    /**
     * <code>required .IM.Enum.LoginStatus status = 1;</code>
     */
    public boolean hasStatus() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .IM.Enum.LoginStatus status = 1;</code>
     */
    public me.ele.cs.push.protobuf.IMEnum.LoginStatus getStatus() {
      me.ele.cs.push.protobuf.IMEnum.LoginStatus result = me.ele.cs.push.protobuf.IMEnum.LoginStatus.valueOf(status_);
      return result == null ? me.ele.cs.push.protobuf.IMEnum.LoginStatus.SUCESS : result;
    }
    /**
     * <code>required .IM.Enum.LoginStatus status = 1;</code>
     */
    private void setStatus(me.ele.cs.push.protobuf.IMEnum.LoginStatus value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000001;
      status_ = value.getNumber();
    }
    /**
     * <code>required .IM.Enum.LoginStatus status = 1;</code>
     */
    private void clearStatus() {
      bitField0_ = (bitField0_ & ~0x00000001);
      status_ = 1;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, status_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, status_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static me.ele.cs.push.protobuf.IMMessage.LoginResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return parser().parseFrom(data);
    }
    public static me.ele.cs.push.protobuf.IMMessage.LoginResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return parser().parseFrom(data, extensionRegistry);
    }
    public static me.ele.cs.push.protobuf.IMMessage.LoginResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return parser().parseFrom(data);
    }
    public static me.ele.cs.push.protobuf.IMMessage.LoginResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return parser().parseFrom(data, extensionRegistry);
    }
    public static me.ele.cs.push.protobuf.IMMessage.LoginResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parser().parseFrom(input);
    }
    public static me.ele.cs.push.protobuf.IMMessage.LoginResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parser().parseFrom(input, extensionRegistry);
    }
    public static me.ele.cs.push.protobuf.IMMessage.LoginResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parser().parseDelimitedFrom(input);
    }
    public static me.ele.cs.push.protobuf.IMMessage.LoginResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parser().parseDelimitedFrom(input, extensionRegistry);
    }
    public static me.ele.cs.push.protobuf.IMMessage.LoginResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return parser().parseFrom(input);
    }
    public static me.ele.cs.push.protobuf.IMMessage.LoginResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parser().parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(me.ele.cs.push.protobuf.IMMessage.LoginResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code IM.Message.LoginResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          me.ele.cs.push.protobuf.IMMessage.LoginResponse, Builder> implements
        // @@protoc_insertion_point(builder_implements:IM.Message.LoginResponse)
        me.ele.cs.push.protobuf.IMMessage.LoginResponseOrBuilder {
      // Construct using me.ele.cs.push.protobuf.IMMessage.LoginResponse.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>required .IM.Enum.LoginStatus status = 1;</code>
       */
      public boolean hasStatus() {
        return instance.hasStatus();
      }
      /**
       * <code>required .IM.Enum.LoginStatus status = 1;</code>
       */
      public me.ele.cs.push.protobuf.IMEnum.LoginStatus getStatus() {
        return instance.getStatus();
      }
      /**
       * <code>required .IM.Enum.LoginStatus status = 1;</code>
       */
      public Builder setStatus(me.ele.cs.push.protobuf.IMEnum.LoginStatus value) {
        copyOnWrite();
        instance.setStatus(value);
        return this;
      }
      /**
       * <code>required .IM.Enum.LoginStatus status = 1;</code>
       */
      public Builder clearStatus() {
        copyOnWrite();
        instance.clearStatus();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:IM.Message.LoginResponse)
    }
    private byte memoizedIsInitialized = -1;
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case PARSE_PARTIAL_FROM: {
          return new me.ele.cs.push.protobuf.IMMessage.LoginResponse(          (com.google.protobuf.CodedInputStream) arg0,
              (com.google.protobuf.ExtensionRegistryLite) arg1);
        }
        case NEW_INSTANCE: {
          return new me.ele.cs.push.protobuf.IMMessage.LoginResponse(
              com.google.protobuf.Internal.EMPTY_CODED_INPUT_STREAM,
              com.google.protobuf.ExtensionRegistryLite
                  .getEmptyRegistry());
        }
        case IS_INITIALIZED: {
          byte isInitialized = memoizedIsInitialized;
          if (isInitialized == 1) return DEFAULT_INSTANCE;
          if (isInitialized == 0) return null;

          boolean shouldMemoize = ((Boolean) arg0).booleanValue();
          if (!hasStatus()) {
            if (shouldMemoize) {
              memoizedIsInitialized = 0;
            }
            return null;
          }
          if (shouldMemoize) memoizedIsInitialized = 1;
          return DEFAULT_INSTANCE;

        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case MERGE_FROM: {
          if (arg0 == me.ele.cs.push.protobuf.IMMessage.LoginResponse.getDefaultInstance()) return this;
          me.ele.cs.push.protobuf.IMMessage.LoginResponse other = (me.ele.cs.push.protobuf.IMMessage.LoginResponse) arg0;
          if (other.hasStatus()) {
            setStatus(other.getStatus());
          }
          this.mergeUnknownFields(other.unknownFields);
          return this;
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (me.ele.cs.push.protobuf.IMMessage.LoginResponse.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:IM.Message.LoginResponse)
    private static final me.ele.cs.push.protobuf.IMMessage.LoginResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new LoginResponse(
          com.google.protobuf.Internal
              .EMPTY_CODED_INPUT_STREAM,
          com.google.protobuf.ExtensionRegistryLite
              .getEmptyRegistry());
    }

    public static me.ele.cs.push.protobuf.IMMessage.LoginResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<LoginResponse> PARSER;

    public static com.google.protobuf.Parser<LoginResponse> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface PushMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:IM.Message.PushMessage)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>required uint64 message_id = 1;</code>
     */
    boolean hasMessageId();
    /**
     * <code>required uint64 message_id = 1;</code>
     */
    long getMessageId();

    /**
     * <code>required string content = 2;</code>
     */
    boolean hasContent();
    /**
     * <code>required string content = 2;</code>
     */
    java.lang.String getContent();
    /**
     * <code>required string content = 2;</code>
     */
    com.google.protobuf.ByteString
        getContentBytes();

    /**
     * <code>optional string redirect_url = 3;</code>
     */
    boolean hasRedirectUrl();
    /**
     * <code>optional string redirect_url = 3;</code>
     */
    java.lang.String getRedirectUrl();
    /**
     * <code>optional string redirect_url = 3;</code>
     */
    com.google.protobuf.ByteString
        getRedirectUrlBytes();
  }
  /**
   * Protobuf type {@code IM.Message.PushMessage}
   */
  public  static final class PushMessage extends
      com.google.protobuf.GeneratedMessageLite<
          PushMessage, PushMessage.Builder> implements
      // @@protoc_insertion_point(message_implements:IM.Message.PushMessage)
      PushMessageOrBuilder {
    private PushMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      messageId_ = 0L;
      content_ = "";
      redirectUrl_ = "";
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(tag, input)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              messageId_ = input.readUInt64();
              break;
            }
            case 18: {
              String s = input.readString();
              bitField0_ |= 0x00000002;
              content_ = s;
              break;
            }
            case 26: {
              String s = input.readString();
              bitField0_ |= 0x00000004;
              redirectUrl_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        doneParsing();
      }
    }
    private int bitField0_;
    public static final int MESSAGE_ID_FIELD_NUMBER = 1;
    private long messageId_;
    /**
     * <code>required uint64 message_id = 1;</code>
     */
    public boolean hasMessageId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required uint64 message_id = 1;</code>
     */
    public long getMessageId() {
      return messageId_;
    }
    /**
     * <code>required uint64 message_id = 1;</code>
     */
    private void setMessageId(long value) {
      bitField0_ |= 0x00000001;
      messageId_ = value;
    }
    /**
     * <code>required uint64 message_id = 1;</code>
     */
    private void clearMessageId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      messageId_ = 0L;
    }

    public static final int CONTENT_FIELD_NUMBER = 2;
    private java.lang.String content_;
    /**
     * <code>required string content = 2;</code>
     */
    public boolean hasContent() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string content = 2;</code>
     */
    public java.lang.String getContent() {
      return content_;
    }
    /**
     * <code>required string content = 2;</code>
     */
    public com.google.protobuf.ByteString
        getContentBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(content_);
    }
    /**
     * <code>required string content = 2;</code>
     */
    private void setContent(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      content_ = value;
    }
    /**
     * <code>required string content = 2;</code>
     */
    private void clearContent() {
      bitField0_ = (bitField0_ & ~0x00000002);
      content_ = getDefaultInstance().getContent();
    }
    /**
     * <code>required string content = 2;</code>
     */
    private void setContentBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      content_ = value.toStringUtf8();
    }

    public static final int REDIRECT_URL_FIELD_NUMBER = 3;
    private java.lang.String redirectUrl_;
    /**
     * <code>optional string redirect_url = 3;</code>
     */
    public boolean hasRedirectUrl() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string redirect_url = 3;</code>
     */
    public java.lang.String getRedirectUrl() {
      return redirectUrl_;
    }
    /**
     * <code>optional string redirect_url = 3;</code>
     */
    public com.google.protobuf.ByteString
        getRedirectUrlBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(redirectUrl_);
    }
    /**
     * <code>optional string redirect_url = 3;</code>
     */
    private void setRedirectUrl(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
      redirectUrl_ = value;
    }
    /**
     * <code>optional string redirect_url = 3;</code>
     */
    private void clearRedirectUrl() {
      bitField0_ = (bitField0_ & ~0x00000004);
      redirectUrl_ = getDefaultInstance().getRedirectUrl();
    }
    /**
     * <code>optional string redirect_url = 3;</code>
     */
    private void setRedirectUrlBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
      redirectUrl_ = value.toStringUtf8();
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt64(1, messageId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeString(2, getContent());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeString(3, getRedirectUrl());
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, messageId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getContent());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(3, getRedirectUrl());
      }
      size += unknownFields.getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static me.ele.cs.push.protobuf.IMMessage.PushMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return parser().parseFrom(data);
    }
    public static me.ele.cs.push.protobuf.IMMessage.PushMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return parser().parseFrom(data, extensionRegistry);
    }
    public static me.ele.cs.push.protobuf.IMMessage.PushMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return parser().parseFrom(data);
    }
    public static me.ele.cs.push.protobuf.IMMessage.PushMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return parser().parseFrom(data, extensionRegistry);
    }
    public static me.ele.cs.push.protobuf.IMMessage.PushMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parser().parseFrom(input);
    }
    public static me.ele.cs.push.protobuf.IMMessage.PushMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parser().parseFrom(input, extensionRegistry);
    }
    public static me.ele.cs.push.protobuf.IMMessage.PushMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parser().parseDelimitedFrom(input);
    }
    public static me.ele.cs.push.protobuf.IMMessage.PushMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parser().parseDelimitedFrom(input, extensionRegistry);
    }
    public static me.ele.cs.push.protobuf.IMMessage.PushMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return parser().parseFrom(input);
    }
    public static me.ele.cs.push.protobuf.IMMessage.PushMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parser().parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(me.ele.cs.push.protobuf.IMMessage.PushMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code IM.Message.PushMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          me.ele.cs.push.protobuf.IMMessage.PushMessage, Builder> implements
        // @@protoc_insertion_point(builder_implements:IM.Message.PushMessage)
        me.ele.cs.push.protobuf.IMMessage.PushMessageOrBuilder {
      // Construct using me.ele.cs.push.protobuf.IMMessage.PushMessage.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>required uint64 message_id = 1;</code>
       */
      public boolean hasMessageId() {
        return instance.hasMessageId();
      }
      /**
       * <code>required uint64 message_id = 1;</code>
       */
      public long getMessageId() {
        return instance.getMessageId();
      }
      /**
       * <code>required uint64 message_id = 1;</code>
       */
      public Builder setMessageId(long value) {
        copyOnWrite();
        instance.setMessageId(value);
        return this;
      }
      /**
       * <code>required uint64 message_id = 1;</code>
       */
      public Builder clearMessageId() {
        copyOnWrite();
        instance.clearMessageId();
        return this;
      }

      /**
       * <code>required string content = 2;</code>
       */
      public boolean hasContent() {
        return instance.hasContent();
      }
      /**
       * <code>required string content = 2;</code>
       */
      public java.lang.String getContent() {
        return instance.getContent();
      }
      /**
       * <code>required string content = 2;</code>
       */
      public com.google.protobuf.ByteString
          getContentBytes() {
        return instance.getContentBytes();
      }
      /**
       * <code>required string content = 2;</code>
       */
      public Builder setContent(
          java.lang.String value) {
        copyOnWrite();
        instance.setContent(value);
        return this;
      }
      /**
       * <code>required string content = 2;</code>
       */
      public Builder clearContent() {
        copyOnWrite();
        instance.clearContent();
        return this;
      }
      /**
       * <code>required string content = 2;</code>
       */
      public Builder setContentBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setContentBytes(value);
        return this;
      }

      /**
       * <code>optional string redirect_url = 3;</code>
       */
      public boolean hasRedirectUrl() {
        return instance.hasRedirectUrl();
      }
      /**
       * <code>optional string redirect_url = 3;</code>
       */
      public java.lang.String getRedirectUrl() {
        return instance.getRedirectUrl();
      }
      /**
       * <code>optional string redirect_url = 3;</code>
       */
      public com.google.protobuf.ByteString
          getRedirectUrlBytes() {
        return instance.getRedirectUrlBytes();
      }
      /**
       * <code>optional string redirect_url = 3;</code>
       */
      public Builder setRedirectUrl(
          java.lang.String value) {
        copyOnWrite();
        instance.setRedirectUrl(value);
        return this;
      }
      /**
       * <code>optional string redirect_url = 3;</code>
       */
      public Builder clearRedirectUrl() {
        copyOnWrite();
        instance.clearRedirectUrl();
        return this;
      }
      /**
       * <code>optional string redirect_url = 3;</code>
       */
      public Builder setRedirectUrlBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setRedirectUrlBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:IM.Message.PushMessage)
    }
    private byte memoizedIsInitialized = -1;
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case PARSE_PARTIAL_FROM: {
          return new me.ele.cs.push.protobuf.IMMessage.PushMessage(          (com.google.protobuf.CodedInputStream) arg0,
              (com.google.protobuf.ExtensionRegistryLite) arg1);
        }
        case NEW_INSTANCE: {
          return new me.ele.cs.push.protobuf.IMMessage.PushMessage(
              com.google.protobuf.Internal.EMPTY_CODED_INPUT_STREAM,
              com.google.protobuf.ExtensionRegistryLite
                  .getEmptyRegistry());
        }
        case IS_INITIALIZED: {
          byte isInitialized = memoizedIsInitialized;
          if (isInitialized == 1) return DEFAULT_INSTANCE;
          if (isInitialized == 0) return null;

          boolean shouldMemoize = ((Boolean) arg0).booleanValue();
          if (!hasMessageId()) {
            if (shouldMemoize) {
              memoizedIsInitialized = 0;
            }
            return null;
          }
          if (!hasContent()) {
            if (shouldMemoize) {
              memoizedIsInitialized = 0;
            }
            return null;
          }
          if (shouldMemoize) memoizedIsInitialized = 1;
          return DEFAULT_INSTANCE;

        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case MERGE_FROM: {
          if (arg0 == me.ele.cs.push.protobuf.IMMessage.PushMessage.getDefaultInstance()) return this;
          me.ele.cs.push.protobuf.IMMessage.PushMessage other = (me.ele.cs.push.protobuf.IMMessage.PushMessage) arg0;
          if (other.hasMessageId()) {
            setMessageId(other.getMessageId());
          }
          if (other.hasContent()) {
            bitField0_ |= 0x00000002;
            content_ = other.content_;
            
          }
          if (other.hasRedirectUrl()) {
            bitField0_ |= 0x00000004;
            redirectUrl_ = other.redirectUrl_;
            
          }
          this.mergeUnknownFields(other.unknownFields);
          return this;
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (me.ele.cs.push.protobuf.IMMessage.PushMessage.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:IM.Message.PushMessage)
    private static final me.ele.cs.push.protobuf.IMMessage.PushMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new PushMessage(
          com.google.protobuf.Internal
              .EMPTY_CODED_INPUT_STREAM,
          com.google.protobuf.ExtensionRegistryLite
              .getEmptyRegistry());
    }

    public static me.ele.cs.push.protobuf.IMMessage.PushMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<PushMessage> PARSER;

    public static com.google.protobuf.Parser<PushMessage> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
